### ISSUE TITLE
dear friend

### ISSUE THREAD

**Issue by Yunworthy** [ravijo/baxter_moveit_tutorial#1]
i use kinect_baxter_calibration to get a transformation matrix, but how do I use it in real work? Do you have a similar program that I want to learn.thank you very much for your help

**Comment by ravijo** [comment]
> i use kinect_baxter_calibration to get a transformation matrix, but how do I use it in real work

I think you are looking for an example showing how to use transformations inside ROS. Please check [this](https://gist.github.com/ravijo/cb560eeb1b514a13dc899aef5e6300c0)

Make sure you have published the transformation before running the above code. In other words, please do not forget to run the below command-

```
roslaunch kinect_baxter_calibration publish_calibration.launch
```

PS: I didn't understand how this issue is related to [baxter_moveit_tutorial](https://github.com/ravijo/baxter_moveit_tutorial). If I misunderstood you, do not hesitate to correct me.
